const countryList = {
    AED: "AE",
    AFN: "AF",
    XCD: "AG",
    ALL: "AL",
    AMD: "AM",
    ANG: "AN",
    AOA: "AO",
    AQD: "AQ",
    ARS: "AR",
    AZN: "AZ",
    INR: "IN",
    USD: "US",
    EUR: "AN",
    AUD: "AU",
}